AWSTemplateFormatVersion: 2010-09-09
Description: Application LoadBalancer on 2 Application Server

Resources:
  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: aamirAPLB
      Scheme: internet-facing
      SecurityGroups: 
        - !ImportValue aamirVPC-APLBSG
      Subnets:
        - !ImportValue aamirVPC-PublicSubnet01
        - !ImportValue aamirVPC-PublicSubnet02
      Tags:
        - Key: Name
          Value: aamirAPLB

  LoadBalancerListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref LoadBalancer
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref DefaultTargetGroup


  DefaultTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckEnabled: true
      HealthCheckIntervalSeconds: 6
      HealthCheckPath: "/StudentDataApp/"
      HealthCheckPort: 'traffic-port'
      HealthCheckProtocol: 'HTTP'
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 3
      Name: aamirTargetGroup
      VpcId: !ImportValue aamirVPC-VPC
      Port: 80
      Protocol: HTTP
      TargetType: 'instance'
      Tags:
        - Key: Name
          Value: Target_01

Outputs:
  LoadBalancer:
    Description: A reference to the Application Load Balancer
    Value: !Ref LoadBalancer
    Export:
      Name: !Sub "AppLoadBalancer-LoadBalancer"

  LoadBalancerUrl:
    Description: The URL of the ALB
    Value: !GetAtt LoadBalancer.DNSName
    Export:
      Name: !Sub "AppLoadBalancer-LoadBalancerUrl"

  TargetGroupName:
    Description: A reference to a port 80 listener
    Value: !Ref DefaultTargetGroup
    Export:
      Name: !Sub "AppLoadBalancer-DefaultTargetGroup"    
