AWSTemplateFormatVersion: 2010-09-09
Description: Parent Stack of Nested ones

Parameters:
  VPCId:
    Type: AWS::EC2::VPC::Id
  VPCCidr:
    Type: String
    Default: 172.31.0.0/20
  PublicSubnets:
    Type: List<AWS::EC2::Subnet::Id>
  PrivateSubnets:
    Type: List<AWS::EC2::Subnet::Id>
  KeyName: 
    Description: Name of an existing EC2 key pair for SSH access to the EC2 instance
    Type: "AWS::EC2::KeyPair::KeyName"
    Default: "aamirKP1"
  Ec2AmiId:
    Type: String
    Default: "ami-074cce78125f09d61"
    
  # InstaceTypeParam:
  #   Type: "String"
  #   Default: "t2.micro"
  #   AllowedValues: 
  #     - "t2.micro"
  #     - "m3.medium"
  #     - "m3.large"
  #     - "c3.large"
  #     - "c3.xlarge"
  #   ConstraintDescription: Must be one of them



Resources:
  EfsStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "https://cf-templates-z0sc5gmdoroj-us-east-2.s3.us-east-2.amazonaws.com/efs.yml"
      TimeoutInMinutes: 30
      Parameters: 
        PrivateSubnetId1: !Select [ 0, !Ref PrivateSubnets ]
        PrivateSubnetId2: !Select [ 1, !Ref PrivateSubnets ]
        VPCId: !Ref VPCId
        VPCCidr: !Ref VPCCidr

  LoadBalancerStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "https://cf-templates-z0sc5gmdoroj-us-east-2.s3.us-east-2.amazonaws.com/alb.yml"
      TimeoutInMinutes: 30
      Parameters: 
        VPCId: !Ref VPCId
        PublicSubnets: !Join [",", !Ref PublicSubnets]

  AutoScallingStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: 
      - LoadBalancerStack
      - EfsStack
    Properties: 
      TemplateURL: "https://cf-templates-z0sc5gmdoroj-us-east-2.s3.us-east-2.amazonaws.com/asg.yml"
      TimeoutInMinutes: 30
      Parameters: 
        Ec2AmiId: !Ref Ec2AmiId
        KeyName: !Ref KeyName
        PrivateSubnets: !Join [",", !Ref PrivateSubnets]
        VPCId: !Ref VPCId
        VPCCidr: !Ref VPCCidr


  # MyAutoScallingStack:
  #   Type: AWS::CloudFormation::Stack
  #   DependsOn: MyLoadBalancerStack
  #   Properties: 
  #     TemplateURL: "https://cf-templates-z0sc5gmdoroj-us-east-2.s3.us-east-2.amazonaws.com/asg.yml"
  #     TimeoutInMinutes: 30
  #     Parameters: 
  #       RoleName: !Ref "RoleName"
  #       InstaceTypeParam: !Ref "InstaceTypeParam"
  #       KeyName: !Ref "KeyName"


  # MyDbStack:
  #   Type: AWS::CloudFormation::Stack
  #   DependsOn: MyVpcStack
  #   Properties:  
  #     TemplateURL: "https://cf-templates-10v3kub72h1yp-us-west-1.s3-us-west-1.amazonaws.com/DBServer.yaml"
  #     TimeoutInMinutes: 30
  #     Parameters: 
  #       InstaceTypeParam: !Ref "InstaceTypeParam"
  #       KeyName: !Ref "KeyName"
  #       AZsSelection: !GetAtt "MyVpcStack.Outputs.PVSUB01r"
  #       SG: !GetAtt "MyVpcStack.Outputs.DBSGr"


  
  # MyLoadBalancerStack:
  #   Type: AWS::CloudFormation::Stack
  #   DependsOn: MyVpcStack
  #   Properties:  
  #     TemplateURL: "https://cf-templates-10v3kub72h1yp-us-west-1.s3-us-west-1.amazonaws.com/AppLoadBalancer.yaml"
  #     TimeoutInMinutes: 30

          

        